<a href="https://colab.research.google.com/github/WilliamAshbee/computervision/blob/main/homework2/problem_6_integralimage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
a = np.zeros((5,5))
b = np.random.randint(1,20,[5,5])


In [20]:
b

array([[ 6,  4, 15,  9, 17],
       [ 4, 10,  4,  8, 19],
       [18,  9, 15, 18, 16],
       [ 6, 15, 14,  8,  5],
       [13, 14,  7,  6, 17]])

In [41]:
def myIntegralImage(img):
  temp = np.pad(img, 1, 'constant', constant_values=0)
  for j in range(1,temp.shape[0]-1):
    for i in range(1,temp.shape[1]-1):
      temp[j,i] = temp[j-1,i]+temp[j,i-1]+temp[j,i]-temp[j-1,i-1]
       
  return temp

In [42]:
print(b)
print(myIntegralImage(b))

[[ 6  4 15  9 17]
 [ 4 10  4  8 19]
 [18  9 15 18 16]
 [ 6 15 14  8  5]
 [13 14  7  6 17]]
[[  0   0   0   0   0   0   0]
 [  0   6  10  25  34  51   0]
 [  0  10  24  43  60  96   0]
 [  0  28  51  85 120 172   0]
 [  0  34  72 120 163 220   0]
 [  0  47  99 154 203 277   0]
 [  0   0   0   0   0   0   0]]


In [43]:
np.sum(b)

277